# Turns out there is no way yet to only configure this for security updates
# So the file is renamed to wait for that config option to be available
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
