name: 'arm-none-eabi-gcc GNU Arm Embedded Toolchain'
description: 'Install arm-none-eabi-gcc Arm Embedded Toolchain.'
author: 'Carlos Pereira Atencio'
inputs:
  release:
    description: 'GNU Embedded Toolchain for Arm release name (e.g. "10.3-2021.07").'
    default: 'latest'
    required: false
  path-env-var:
    description: 'Name for an environmental variable to be created with the toolchain path.'
    required: false
outputs:
  path:
    description: 'Path to the bin folder with the toolchain executables.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'blue'
