name: 'arm-none-eabi-gcc GNU Arm Embedded Toolchain'
description: 'Set up arm-none-eabi-gcc and add it to the PATH.'
author: 'Carlos Pereira Atencio'
inputs:
  release:
    description: 'GNU Embedded Toolchain for Arm release name (e.g. "10.3-2021.07").'
  directory:
    description: 'Directory to unpack GCC to. Defaults to a temporary directory.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'green'
